### ISSUE TITLE
Modern public domain mobile-optimized CLOS MOP specification

### ISSUE THREAD

**Issue by Hexstream** [GustavBertram/awesome-common-lisp-learning-list#5]
I'm not sure how you want to incorporate that information, but as of 15 October 2017, [my modern public domain mobile-optimized version of the CLOS MOP specification](https://clos-mop.hexstreamsoft.com/) (chapters 5 and 6 of AMOP) _quite solidly_ obsoletes all previous versions.

**Comment by GustavBertram** [comment]
Thanks Jean-Philippe, will make the update!

**Comment by Hexstream** [comment]
Awesome!! Thank you!!
